"""Tests for the sync driver.

The pure pieces — manifest parsing + out-path guard, the bindings buf.gen.yaml,
the binding-file closure, service validation, the out-directory guard, and the
SOURCE.txt pin record — run offline. `_generate_bindings` is tested with codefly
stubbed so the vendoring (buf output -> `out/`) is exercised without Docker. The
full `sync` (real `codefly generate proto` + BSR fetch) is not run here.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

import pytest
import yaml

from solution_runtime.sdk import sync

FIXTURES = Path(__file__).parent / "fixtures"


def _write_manifest(tmp_path: Path, out: str = "backend/_sdk", services: str = "[AuditService]") -> Path:
    path = tmp_path / "solution-sdk.yaml"
    path.write_text(
        textwrap.dedent(
            f"""
            version: 1
            out: {out}
            dependencies:
              - module: accounts
                package: saas.accounts.v1
                source:
                  repo: https://github.com/codefly-dev/module-saas-starter
                  ref: a44ac5aa0b9d019ad8ad659b474c36d81bf9ed50
                  subdir: module/services/accounts/proto
                services: {services}
            """
        )
    )
    return path


def _fixture_descriptors(tmp_path: Path):
    proto_root = tmp_path / "proto"
    shutil.copytree(FIXTURES, proto_root)
    (proto_root / "buf.yaml").write_text(yaml.safe_dump({"version": "v2", "modules": [{"path": "."}]}))
    subprocess.run(["buf", "dep", "update"], cwd=proto_root, check=True)
    return proto_root, sync._descriptor_set(proto_root)


def test_load_manifest(tmp_path):
    manifest = sync.load_manifest(_write_manifest(tmp_path))

    assert manifest.out == (tmp_path / "backend/_sdk").resolve()
    (dependency,) = manifest.dependencies
    assert dependency.module == "accounts"
    assert dependency.package == "saas.accounts.v1"
    assert dependency.services == ("AuditService",)
    assert dependency.source.ref == "a44ac5aa0b9d019ad8ad659b474c36d81bf9ed50"


@pytest.mark.parametrize("bad_out", [".", "../elsewhere", "/tmp/abs"])
def test_load_manifest_rejects_out_outside_solution(tmp_path, bad_out):
    with pytest.raises(SystemExit, match="within"):
        sync.load_manifest(_write_manifest(tmp_path, out=bad_out))


def test_bindings_buf_gen_is_messages_only_and_targets_scratch():
    document = yaml.safe_load(sync.render_bindings_buf_gen("_gen"))

    remotes = [p["remote"] for p in document["plugins"]]
    assert remotes == ["buf.build/protocolbuffers/python", "buf.build/protocolbuffers/pyi"]
    assert all(p["out"] == "_gen" for p in document["plugins"])  # not ".", which codefly writes to the proto dir


def test_write_source_records_every_pin(tmp_path):
    manifest = sync.load_manifest(_write_manifest(tmp_path))
    tmp_path.joinpath("out").mkdir()
    sync.write_source(tmp_path / "out", manifest.dependencies)

    text = (tmp_path / "out" / "SOURCE.txt").read_text()
    assert "accounts: saas.accounts.v1" in text
    assert "module-saas-starter@a44ac5aa0b9d019ad8ad659b474c36d81bf9ed50" in text


def test_prepare_out_refuses_foreign_directory(tmp_path):
    out = tmp_path / "backend"
    out.mkdir()
    (out / "main.py").write_text("print('real code')")

    with pytest.raises(SystemExit, match="refusing to overwrite"):
        sync._prepare_out(out)

    assert (out / "main.py").is_file()  # untouched


def test_prepare_out_replaces_prior_sdk(tmp_path):
    out = tmp_path / "_sdk"
    out.mkdir()
    (out / "SOURCE.txt").write_text("Generated by solution-sdk.")
    (out / "stale.py").write_text("old")

    sync._prepare_out(out)

    assert out.is_dir()
    assert not (out / "stale.py").exists()


def test_generate_bindings_vendors_scratch_into_out(tmp_path, monkeypatch):
    proto_root = tmp_path / "proto"
    proto_root.mkdir()
    out = tmp_path / "_sdk"
    out.mkdir()
    calls = []

    def fake_run(command, **kwargs):
        calls.append(command)
        generated = proto_root / "_gen" / "saas" / "accounts" / "v1"
        generated.mkdir(parents=True, exist_ok=True)
        (generated / "audit_pb2.py").write_text("# generated")
        return subprocess.CompletedProcess(command, 0)

    monkeypatch.setattr(sync.subprocess, "run", fake_run)
    sync._generate_bindings(proto_root, ["saas/accounts/v1/audit.proto"], out)

    # bindings landed in `out`, not the (temporary) proto dir
    assert (out / "saas" / "accounts" / "v1" / "audit_pb2.py").is_file()
    codefly = next(c for c in calls if c[:3] == ["codefly", "generate", "proto"])
    assert "--path" in codefly and "saas/accounts/v1/audit.proto" in codefly


@pytest.mark.skipif(shutil.which("buf") is None, reason="buf not installed")
def test_validate_services_rejects_unknown(tmp_path):
    _, descriptors = _fixture_descriptors(tmp_path)
    dependency = sync.Dependency("accounts", "saas.accounts.v1", sync.Source("r", "ref", "."), ("NoSuchService",))
    with pytest.raises(SystemExit, match="declared services not found"):
        sync._validate_services(descriptors, dependency)


@pytest.mark.skipif(shutil.which("buf") is None, reason="buf not installed")
def test_binding_paths_is_the_referenced_closure(tmp_path):
    proto_root, descriptors = _fixture_descriptors(tmp_path)
    dependency = sync.Dependency("accounts", "saas.accounts.v1", sync.Source("r", "ref", "."), ("AuditService",))

    paths = sync._binding_paths(descriptors, proto_root, dependency)

    assert paths == ["saas/accounts/v1/audit.proto"]  # the service file only
    assert not any("google/protobuf" in p for p in paths)  # well-known deps stay external


@pytest.mark.skipif(shutil.which("buf") is None, reason="buf not installed")
def test_generate_facade_from_descriptor(tmp_path):
    _, descriptors = _fixture_descriptors(tmp_path)
    out = tmp_path / "_sdk"
    out.mkdir()
    dependency = sync.Dependency("accounts", "saas.accounts.v1", sync.Source("r", "ref", "."), ("AuditService",))

    sync._generate_facade(descriptors, dependency, out)

    facade = (out / "accounts.py").read_text()
    assert "def accounts(gateway):" in facade
    assert '"/saas.accounts.v1.AuditService/QueryAuditLog"' in facade
    assert "IdentityService" not in facade  # declared subset honored


# --- the shim ------------------------------------------------------------
#
# When a solution.codefly.yaml is present the contracts live in the composed
# module package, so `solution-sdk sync` hands off to `codefly sync
# solution-sdk`. Otherwise the legacy fetch-and-vendor path runs, once, under a
# deprecation warning.


def _fake_codefly(bin_dir: Path, argv_log: Path, exit_code: int = 0) -> None:
    bin_dir.mkdir(parents=True, exist_ok=True)
    codefly = bin_dir / "codefly"
    codefly.write_text(
        textwrap.dedent(
            f"""\
            #!/usr/bin/env python3
            import sys
            with open({str(argv_log)!r}, "w") as handle:
                handle.write("\\n".join(sys.argv[1:]))
            sys.exit({exit_code})
            """
        )
    )
    codefly.chmod(0o755)


@pytest.mark.parametrize("exit_code", [0, 3])
def test_main_shims_to_codefly_when_solution_manifest_present(tmp_path, exit_code):
    solution = tmp_path / "solution"
    solution.mkdir()
    (solution / "solution.codefly.yaml").write_text("api:\n  consumes: []\n")
    bin_dir = tmp_path / "bin"
    argv_log = tmp_path / "codefly-argv.txt"
    _fake_codefly(bin_dir, argv_log, exit_code)

    env = {**os.environ, "PATH": f"{bin_dir}{os.pathsep}{os.environ['PATH']}"}
    result = subprocess.run(
        [sys.executable, "-m", "solution_runtime.sdk.sync", "sync"],
        cwd=solution,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == exit_code  # child exit code propagated through exec
    assert argv_log.read_text().splitlines() == ["sync", "solution-sdk", "--language", "python"]
    assert "superseded by api.consumes" in result.stderr
    assert "ignoring -f" not in result.stderr  # no -f passed, nothing to announce


def test_main_shim_announces_ignored_explicit_manifest(tmp_path):
    solution = tmp_path / "solution"
    solution.mkdir()
    (solution / "solution.codefly.yaml").write_text("api:\n  consumes: []\n")
    bin_dir = tmp_path / "bin"
    _fake_codefly(bin_dir, tmp_path / "codefly-argv.txt")

    env = {**os.environ, "PATH": f"{bin_dir}{os.pathsep}{os.environ['PATH']}"}
    result = subprocess.run(
        [sys.executable, "-m", "solution_runtime.sdk.sync", "sync", "-f", "legacy.yaml"],
        cwd=solution,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0
    assert "ignoring -f legacy.yaml" in result.stderr  # the override is not silent


def test_main_shim_reports_missing_codefly_cleanly(tmp_path, monkeypatch):
    (tmp_path / "solution.codefly.yaml").write_text("api:\n  consumes: []\n")
    monkeypatch.setattr(sync.os, "execvp", lambda *a: (_ for _ in ()).throw(FileNotFoundError()))

    with pytest.raises(SystemExit, match="codefly not found on PATH"):
        sync.main(["sync", "-f", str(tmp_path / "solution-sdk.yaml")])


def test_main_shims_from_parent_directory(tmp_path):
    root = tmp_path / "workspace"
    (root / ".git").mkdir(parents=True)
    (root / "solution.codefly.yaml").write_text("api:\n  consumes: []\n")
    nested = root / "services" / "backend"
    nested.mkdir(parents=True)
    bin_dir = tmp_path / "bin"
    argv_log = tmp_path / "codefly-argv.txt"
    _fake_codefly(bin_dir, argv_log)

    env = {**os.environ, "PATH": f"{bin_dir}{os.pathsep}{os.environ['PATH']}"}
    result = subprocess.run(
        [sys.executable, "-m", "solution_runtime.sdk.sync", "sync"],
        cwd=nested,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0
    assert argv_log.is_file()  # found solution.codefly.yaml two directories up


def test_main_runs_legacy_path_with_single_deprecation_warning(tmp_path, monkeypatch):
    manifest_path = _write_manifest(tmp_path)  # no solution.codefly.yaml alongside it
    synced = []
    # Pin the branch so this in-process main() cannot exec away the test runner
    # if the checkout happens to sit under a workspace with a solution.codefly.yaml.
    monkeypatch.setattr(sync, "_find_solution_manifest", lambda _: None)
    monkeypatch.setattr(sync, "sync", lambda manifest: synced.append(manifest))

    with pytest.warns(DeprecationWarning, match="solution.codefly.yaml") as records:
        assert sync.main(["sync", "-f", str(manifest_path)]) == 0

    assert len(records) == 1  # printed once
    assert len(synced) == 1  # legacy path ran
