"""`solution-sdk` — build a vendored, per-solution SDK from declared dependencies.

A solution owns a `solution-sdk.yaml` listing the module dependencies it calls:

    version: 1
    out: backend/_sdk
    dependencies:
      - module: accounts
        package: saas.accounts.v1
        source:
          repo: https://github.com/codefly-dev/module-saas-starter
          ref: a44ac5aa0b9d019ad8ad659b474c36d81bf9ed50
          subdir: module/services/accounts/proto
        services: [AuditService] # optional: the subset actually used

`solution-sdk sync` fetches each proto at its pinned ref and produces two layers
into `out/`:

1. Message bindings (`*_pb2`), generated by `codefly generate proto` — all proto
   codegen goes through codefly, never a bespoke buf invocation.
2. A gateway-bound facade, emitted from the proto's descriptor by
   `facade_gen`, so a handler writes `accounts(gw).audit().query_audit_log(...)`
   instead of a raw procedure string.

The vendored tree is self-contained and carries a `SOURCE.txt` recording every
pin — the same drift guard `saas-sdk-go` keeps. The vendored root goes on
sys.path (like any generated-proto tree); handlers `import <module>` and call
through the gateway. Only the services declared in `services:` are exposed, and
only the proto files those services reference are generated — one SDK per
solution, carrying only the functionality it declares.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
import warnings
from collections import deque
from dataclasses import dataclass
from pathlib import Path

import yaml
from google.protobuf.compiler import plugin_pb2
from google.protobuf.descriptor_pb2 import FileDescriptorSet

from . import facade_gen


@dataclass(frozen=True)
class Source:
    repo: str
    ref: str
    subdir: str


@dataclass(frozen=True)
class Dependency:
    module: str
    package: str
    source: Source
    services: tuple[str, ...] = ()


@dataclass(frozen=True)
class Manifest:
    out: Path
    dependencies: tuple[Dependency, ...]


def load_manifest(path: Path) -> Manifest:
    raw = yaml.safe_load(path.read_text())
    dependencies = []
    for entry in raw["dependencies"]:
        source = entry["source"]
        dependencies.append(
            Dependency(
                module=entry["module"],
                package=entry["package"],
                source=Source(
                    repo=source["repo"],
                    ref=source["ref"],
                    subdir=source.get("subdir", "."),
                ),
                services=tuple(entry.get("services", ())),
            )
        )
    base = path.parent.resolve()
    out = (base / raw.get("out", "_sdk")).resolve()
    # `sync` deletes and rewrites `out`; confining it strictly below the
    # manifest's own directory keeps a stray `out: .` or `out: ../src` from
    # taking a real source tree with it.
    if base not in out.parents:
        raise SystemExit(f"out must be a directory within {base}, got {raw.get('out', '_sdk')!r}")
    return Manifest(out=out, dependencies=tuple(dependencies))


def render_bindings_buf_gen(out: str) -> str:
    """buf.gen.yaml for the message bindings `codefly generate proto` runs. The
    facade is a separate, descriptor-driven step — it does not belong here, and
    Connect stubs are deliberately omitted (the runtime owns the transport)."""
    return yaml.safe_dump(
        {
            "version": "v2",
            "clean": True,
            "plugins": [
                {"remote": "buf.build/protocolbuffers/python", "out": out},
                {"remote": "buf.build/protocolbuffers/pyi", "out": out},
            ],
        },
        sort_keys=False,
    )


def _fetch_proto(source: Source, into: Path) -> Path:
    subprocess.run(["git", "init", "-q"], cwd=into, check=True)
    subprocess.run(["git", "remote", "add", "origin", source.repo], cwd=into, check=True)
    subprocess.run(
        ["git", "fetch", "-q", "--depth", "1", "origin", source.ref], cwd=into, check=True
    )
    subprocess.run(["git", "checkout", "-q", "FETCH_HEAD"], cwd=into, check=True)
    proto_root = into / source.subdir
    if not proto_root.is_dir():
        raise SystemExit(f"subdir {source.subdir!r} not found in {source.repo}@{source.ref}")
    # Resolve BSR dependencies (protovalidate, googleapis, …) on the host before
    # the descriptor build, matching what codefly's own proto path does inside
    # its companion.
    subprocess.run(["buf", "dep", "update"], cwd=proto_root, check=True)
    return proto_root


def _descriptor_set(proto_root: Path) -> FileDescriptorSet:
    # The whole module plus its imports — the facade's type index and the
    # binding-file closure both need every reachable type, not one package.
    image = subprocess.run(
        ["buf", "build", ".", "--as-file-descriptor-set", "-o", "-"],
        cwd=proto_root,
        check=True,
        capture_output=True,
    ).stdout
    return FileDescriptorSet.FromString(image)


def _validate_services(descriptors: FileDescriptorSet, dependency: Dependency) -> None:
    if not dependency.services:
        return
    available = {
        service.name
        for fd in descriptors.file
        if fd.package == dependency.package
        for service in fd.service
    }
    unknown = set(dependency.services) - available
    if unknown:
        raise SystemExit(
            f"{dependency.module}: declared services not found in {dependency.package}: "
            f"{sorted(unknown)}"
        )


def _binding_paths(descriptors: FileDescriptorSet, proto_root: Path, dependency: Dependency) -> list[str]:
    """Proto files whose bindings the facade will import: the files carrying the
    selected services, plus everything they transitively import that is local to
    this module (well-known / BSR deps stay external). Generating only these
    keeps the SDK minimal without under-generating a referenced type."""
    by_name = {fd.name: fd for fd in descriptors.file}
    selected = frozenset(dependency.services)
    seed = [
        fd.name
        for fd in descriptors.file
        if fd.package == dependency.package
        and any(not selected or service.name in selected for service in fd.service)
    ]
    closure: set[str] = set()
    queue = deque(seed)
    while queue:
        name = queue.popleft()
        if name in closure or not (proto_root / name).is_file():
            continue
        closure.add(name)
        descriptor = by_name.get(name)
        if descriptor is not None:
            queue.extend(descriptor.dependency)
    return sorted(closure)


def _generate_bindings(proto_root: Path, paths: list[str], out: Path) -> None:
    # codefly runs buf from the proto dir, so buf.gen.yaml's `out` is relative to
    # there: generate into a scratch dir inside the (temporary) proto tree, then
    # vendor the result into the solution's `out`.
    scratch = "_gen"
    (proto_root / "buf.gen.yaml").write_text(render_bindings_buf_gen(scratch))
    command = ["codefly", "generate", "proto", "--proto", str(proto_root), "--output", str(proto_root)]
    for path in paths:
        command += ["--path", path]
    subprocess.run(command, check=True)
    shutil.copytree(proto_root / scratch, out, dirs_exist_ok=True)


def _generate_facade(descriptors: FileDescriptorSet, dependency: Dependency, out: Path) -> None:
    request = plugin_pb2.CodeGeneratorRequest()
    request.proto_file.extend(descriptors.file)
    for fd in descriptors.file:
        if fd.package == dependency.package and fd.service:
            request.file_to_generate.append(fd.name)
    parameter = f"module={dependency.module}"
    if dependency.services:
        parameter += f",services={'+'.join(dependency.services)}"
    request.parameter = parameter
    for generated in facade_gen.generate(request).file:
        (out / generated.name).write_text(generated.content)


def write_source(out: Path, dependencies: tuple[Dependency, ...]) -> None:
    lines = ["Generated by solution-sdk. Do not edit vendored files by hand.", ""]
    for dependency in dependencies:
        source = dependency.source
        lines.append(
            f"{dependency.module}: {dependency.package} "
            f"from {source.repo}@{source.ref} ({source.subdir})"
        )
    (out / "SOURCE.txt").write_text("\n".join(lines) + "\n")


def _prepare_out(out: Path) -> None:
    # Only ever delete a directory this tool produced. A prior sync leaves a
    # SOURCE.txt; its absence means `out` points at something we do not own.
    if out.exists():
        if not (out / "SOURCE.txt").is_file():
            raise SystemExit(f"refusing to overwrite {out}: not a solution-sdk output (no SOURCE.txt)")
        shutil.rmtree(out)
    out.mkdir(parents=True)


def sync(manifest: Manifest) -> None:
    _prepare_out(manifest.out)
    for dependency in manifest.dependencies:
        with tempfile.TemporaryDirectory() as tmp:
            proto_root = _fetch_proto(dependency.source, Path(tmp))
            descriptors = _descriptor_set(proto_root)
            _validate_services(descriptors, dependency)
            _generate_bindings(proto_root, _binding_paths(descriptors, proto_root, dependency), manifest.out)
            _generate_facade(descriptors, dependency, manifest.out)
    (manifest.out / "__init__.py").write_text("")
    write_source(manifest.out, manifest.dependencies)


def _workspace_root(start: Path) -> Path:
    """Bounds how far the shim looks upward for a `solution.codefly.yaml`. A
    codefly workspace is rooted at its `codefly.yaml`; a bare git checkout at
    its `.git`. Absent both, the filesystem root bounds the walk."""
    for directory in (start, *start.parents):
        if (directory / "codefly.yaml").is_file() or (directory / ".git").exists():
            return directory
    return Path(start.anchor)


def _find_solution_manifest(start: Path) -> Path | None:
    """`solution.codefly.yaml` in `start` or any parent up to the workspace
    root, whichever comes first. Its presence means the module package now
    carries the contracts and `codefly sync solution-sdk` owns the generation."""
    root = _workspace_root(start)
    for directory in (start, *start.parents):
        candidate = directory / "solution.codefly.yaml"
        if candidate.is_file():
            return candidate
        if directory == root:
            break
    return None


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="solution-sdk")
    parser.add_argument("command", choices=["sync"])
    parser.add_argument(
        "-f",
        "--file",
        default="solution-sdk.yaml",
        help="path to the dependency manifest (default: solution-sdk.yaml)",
    )
    args = parser.parse_args(argv)

    if _find_solution_manifest(Path(args.file).resolve().parent) is not None:
        print(
            "solution-sdk.yaml is superseded by api.consumes in solution.codefly.yaml; "
            "running codefly sync solution-sdk --language python",
            file=sys.stderr,
        )
        try:
            os.execvp("codefly", ["codefly", "sync", "solution-sdk", "--language", "python"])
        except FileNotFoundError:
            raise SystemExit("codefly not found on PATH; install the codefly CLI to run solution-sdk sync")

    warnings.warn(
        "solution-sdk.yaml is deprecated; declare api.consumes in solution.codefly.yaml "
        "and run `codefly sync solution-sdk` instead (see codefly-dev/cli#550). This legacy "
        "path is removed in the next minor.",
        DeprecationWarning,
        stacklevel=2,
    )
    manifest = load_manifest(Path(args.file))
    sync(manifest)
    print(f"vendored {len(manifest.dependencies)} module(s) into {manifest.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
