"""`solution-sdk` — build a vendored, per-solution SDK from declared dependencies.

A solution owns a `solution-sdk.yaml` listing the module dependencies it calls:

    version: 1
    out: backend/_sdk
    dependencies:
      - module: accounts
        package: saas.accounts.v1
        source:
          repo: https://github.com/codefly-dev/module-saas-starter
          ref: a44ac5aa0b9d019ad8ad659b474c36d81bf9ed50
          subdir: module/services/accounts/proto
        services: [AuditService] # optional: the subset actually used

`solution-sdk sync` fetches each proto at its pinned ref and produces two layers
into `out/`:

1. Message bindings (`*_pb2`), generated by `codefly generate proto` — all proto
   codegen goes through codefly, never a bespoke buf invocation.
2. A gateway-bound facade, emitted from the proto's descriptor by
   `facade_gen`, so a handler writes `accounts(gw).audit().query_audit_log(...)`
   instead of a raw procedure string.

The vendored tree is self-contained and carries a `SOURCE.txt` recording every
pin — the same drift guard `saas-sdk-go` keeps. Handlers `from <module> import
<module>` and call through the gateway; only the declared services are present
(one SDK per solution, carrying only the functionality it declares).
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

import yaml
from google.protobuf.compiler import plugin_pb2
from google.protobuf.descriptor_pb2 import FileDescriptorSet

from . import facade_gen


@dataclass(frozen=True)
class Source:
    repo: str
    ref: str
    subdir: str


@dataclass(frozen=True)
class Dependency:
    module: str
    package: str
    source: Source
    services: tuple[str, ...] = ()


@dataclass(frozen=True)
class Manifest:
    out: Path
    dependencies: tuple[Dependency, ...]


def load_manifest(path: Path) -> Manifest:
    raw = yaml.safe_load(path.read_text())
    dependencies = []
    for entry in raw["dependencies"]:
        source = entry["source"]
        dependencies.append(
            Dependency(
                module=entry["module"],
                package=entry["package"],
                source=Source(
                    repo=source["repo"],
                    ref=source["ref"],
                    subdir=source.get("subdir", "."),
                ),
                services=tuple(entry.get("services", ())),
            )
        )
    out = (path.parent / raw.get("out", "_sdk")).resolve()
    return Manifest(out=out, dependencies=tuple(dependencies))


def render_bindings_buf_gen() -> str:
    """buf.gen.yaml for the message bindings `codefly generate proto` runs. The
    facade is a separate, descriptor-driven step — it does not belong here, and
    Connect stubs are deliberately omitted (the runtime owns the transport)."""
    return yaml.safe_dump(
        {
            "version": "v2",
            "clean": True,
            "plugins": [
                {"remote": "buf.build/protocolbuffers/python", "out": "."},
                {"remote": "buf.build/protocolbuffers/pyi", "out": "."},
            ],
        },
        sort_keys=False,
    )


def _package_dir(dependency: Dependency) -> str:
    return str(Path(*dependency.package.split(".")))


def _fetch_proto(source: Source, into: Path) -> Path:
    subprocess.run(["git", "init", "-q"], cwd=into, check=True)
    subprocess.run(["git", "remote", "add", "origin", source.repo], cwd=into, check=True)
    subprocess.run(
        ["git", "fetch", "-q", "--depth", "1", "origin", source.ref], cwd=into, check=True
    )
    subprocess.run(["git", "checkout", "-q", "FETCH_HEAD"], cwd=into, check=True)
    proto_root = into / source.subdir
    if not proto_root.is_dir():
        raise SystemExit(f"subdir {source.subdir!r} not found in {source.repo}@{source.ref}")
    return proto_root


def _generate_bindings(proto_root: Path, dependency: Dependency, out: Path) -> None:
    (proto_root / "buf.gen.yaml").write_text(render_bindings_buf_gen())
    command = ["codefly", "generate", "proto", "--proto", str(proto_root), "--output", str(out)]
    if (proto_root / _package_dir(dependency)).is_dir():
        command += ["--path", _package_dir(dependency)]
    subprocess.run(command, check=True)


def _descriptor_set(proto_root: Path, dependency: Dependency) -> FileDescriptorSet:
    # Run from the proto root so `--path` resolves inside the build context.
    command = ["buf", "build", ".", "--as-file-descriptor-set", "-o", "-"]
    if (proto_root / _package_dir(dependency)).is_dir():
        command += ["--path", _package_dir(dependency)]
    image = subprocess.run(command, cwd=proto_root, check=True, capture_output=True).stdout
    return FileDescriptorSet.FromString(image)


def _generate_facade(proto_root: Path, dependency: Dependency, out: Path) -> None:
    descriptors = _descriptor_set(proto_root, dependency)
    request = plugin_pb2.CodeGeneratorRequest()
    request.proto_file.extend(descriptors.file)
    for fd in descriptors.file:
        if fd.package == dependency.package and fd.service:
            request.file_to_generate.append(fd.name)
    parameter = f"module={dependency.module}"
    if dependency.services:
        parameter += f",services={'+'.join(dependency.services)}"
    request.parameter = parameter
    for generated in facade_gen.generate(request).file:
        (out / generated.name).write_text(generated.content)


def write_source(out: Path, dependencies: tuple[Dependency, ...]) -> None:
    lines = ["Generated by solution-sdk. Do not edit vendored files by hand.", ""]
    for dependency in dependencies:
        source = dependency.source
        lines.append(
            f"{dependency.module}: {dependency.package} "
            f"from {source.repo}@{source.ref} ({source.subdir})"
        )
    (out / "SOURCE.txt").write_text("\n".join(lines) + "\n")


def sync(manifest: Manifest) -> None:
    if manifest.out.exists():
        shutil.rmtree(manifest.out)
    manifest.out.mkdir(parents=True)
    for dependency in manifest.dependencies:
        with tempfile.TemporaryDirectory() as tmp:
            proto_root = _fetch_proto(dependency.source, Path(tmp))
            _generate_bindings(proto_root, dependency, manifest.out)
            _generate_facade(proto_root, dependency, manifest.out)
    (manifest.out / "__init__.py").write_text("")
    write_source(manifest.out, manifest.dependencies)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="solution-sdk")
    parser.add_argument("command", choices=["sync"])
    parser.add_argument(
        "-f",
        "--file",
        default="solution-sdk.yaml",
        help="path to the dependency manifest (default: solution-sdk.yaml)",
    )
    args = parser.parse_args(argv)
    manifest = load_manifest(Path(args.file))
    sync(manifest)
    print(f"vendored {len(manifest.dependencies)} module(s) into {manifest.out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
